//! Init command implementation.

use crate::commands::sync::canonical_locale;
use crate::core::CliError;
use clap::{Parser, ValueEnum};
use fs_err as fs;
use std::collections::BTreeSet;
use std::path::{Path, PathBuf};

/// Runtime manager scaffold generated by `cargo es-fluent init`.
#[derive(Clone, Copy, Debug, Eq, PartialEq, ValueEnum)]
pub enum InitManager {
    /// Standard Rust applications using embedded FTL assets.
    Embedded,
    /// Dioxus client or SSR applications.
    Dioxus,
    /// Bevy applications using Bevy's AssetServer.
    Bevy,
}

impl InitManager {
    fn module_contents(self) -> &'static str {
        match self {
            Self::Embedded => {
                r#"//! es-fluent embedded runtime setup.

pub use es_fluent_manager_embedded::{
    EmbeddedI18n as I18n, EmbeddedInitError, LocalizationError,
};

es_fluent_manager_embedded::define_i18n_module!();
"#
            },
            Self::Dioxus => {
                r#"//! es-fluent Dioxus runtime setup.

pub use es_fluent_manager_dioxus::*;

es_fluent_manager_dioxus::define_i18n_module!();
"#
            },
            Self::Bevy => {
                r#"//! es-fluent Bevy runtime setup.

pub use es_fluent_manager_bevy::*;

es_fluent_manager_bevy::define_i18n_module!();
"#
            },
        }
    }
}

/// Arguments for the init command.
#[derive(Debug, Parser)]
pub struct InitArgs {
    /// Path to the crate root to initialize (defaults to current directory).
    #[arg(short, long)]
    pub path: Option<PathBuf>,

    /// Fallback locale to write into i18n.toml and create under assets_dir.
    #[arg(long, default_value = "en")]
    pub fallback_language: String,

    /// Additional locale directories to create.
    #[arg(long, value_delimiter = ',')]
    pub locales: Vec<String>,

    /// Locale asset directory relative to the crate root.
    #[arg(long, default_value = "assets/locales")]
    pub assets_dir: PathBuf,

    /// Namespace allowlist to write into i18n.toml.
    #[arg(long, value_delimiter = ',')]
    pub namespaces: Vec<String>,

    /// Runtime manager to scaffold.
    #[arg(long, value_enum, default_value = "embedded")]
    pub manager: InitManager,

    /// Also create a build.rs that tracks locale asset changes.
    #[arg(long)]
    pub build_rs: bool,

    /// Also add the matching runtime dependencies to Cargo.toml.
    #[arg(long)]
    pub update_cargo_toml: bool,

    /// Dry run - show what would be created without making changes.
    #[arg(long)]
    pub dry_run: bool,

    /// Overwrite existing generated files when they already exist.
    #[arg(long)]
    pub force: bool,
}

/// Run the init command.
pub fn run_init(args: InitArgs) -> Result<(), CliError> {
    let root = args.path.unwrap_or_else(|| PathBuf::from("."));
    if !root.exists() {
        return Err(CliError::Other(format!(
            "crate root does not exist: {}",
            root.display()
        )));
    }
    if !root.is_dir() {
        return Err(CliError::Other(format!(
            "crate root is not a directory: {}",
            root.display()
        )));
    }

    let fallback_language = canonical_locale(&args.fallback_language)?;
    let mut locales = BTreeSet::from([fallback_language.clone()]);
    for locale in &args.locales {
        locales.insert(canonical_locale(locale)?);
    }

    let assets_dir_toml = args.assets_dir.to_string_lossy().replace('\\', "/");
    let mut config = format!(
        "fallback_language = \"{}\"\nassets_dir = \"{}\"\n",
        fallback_language, assets_dir_toml
    );
    if !args.namespaces.is_empty() {
        let namespaces = args
            .namespaces
            .iter()
            .map(|namespace| format!("\"{}\"", namespace))
            .collect::<Vec<_>>()
            .join(", ");
        config.push_str(&format!("namespaces = [{namespaces}]\n"));
    }

    write_new_file(&root.join("i18n.toml"), &config, args.force, args.dry_run)?;

    for locale in &locales {
        create_dir_all(&root.join(&args.assets_dir).join(locale), args.dry_run)?;
    }

    let src_dir = root.join("src");
    create_dir_all(&src_dir, args.dry_run)?;

    write_new_file(
        &src_dir.join("i18n.rs"),
        args.manager.module_contents(),
        args.force,
        args.dry_run,
    )?;

    ensure_lib_declares_i18n_module(&src_dir.join("lib.rs"), args.force, args.dry_run)?;

    if args.build_rs {
        write_new_file(
            &root.join("build.rs"),
            "fn main() {\n    es_fluent::build::track_i18n_assets();\n}\n",
            args.force,
            args.dry_run,
        )?;
    }

    if args.update_cargo_toml {
        update_cargo_toml(&root, args.manager, args.build_rs, args.dry_run)?;
    }

    if args.dry_run {
        println!("Dry run complete for {}", root.display());
    } else {
        println!("Initialized es-fluent project at {}", root.display());
    }
    println!(
        "Next: add the matching manager crate to Cargo.toml, derive EsFluent types, then run `cargo es-fluent generate`."
    );
    if args.build_rs {
        println!(
            "Also add `es-fluent = {{ version = \"{}\", features = [\"build\"] }}` under [build-dependencies].",
            env!("CARGO_PKG_VERSION")
        );
    }

    Ok(())
}

fn create_dir_all(path: &Path, dry_run: bool) -> Result<(), CliError> {
    if dry_run {
        println!("Would create directory {}", path.display());
        return Ok(());
    }

    fs::create_dir_all(path).map_err(|error| CliError::Other(error.to_string()))
}

fn write_new_file(path: &Path, contents: &str, force: bool, dry_run: bool) -> Result<(), CliError> {
    if path.exists() && !force {
        return Err(CliError::Other(format!(
            "{} already exists; pass --force to overwrite it",
            path.display()
        )));
    }

    if dry_run {
        println!("Would write {}", path.display());
        return Ok(());
    }

    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).map_err(|error| CliError::Other(error.to_string()))?;
    }
    fs::write(path, contents).map_err(|error| CliError::Other(error.to_string()))
}

fn ensure_lib_declares_i18n_module(
    path: &Path,
    force: bool,
    dry_run: bool,
) -> Result<(), CliError> {
    if !path.exists() {
        return write_new_file(path, "pub mod i18n;\n", force, dry_run);
    }

    let contents = fs::read_to_string(path).map_err(|error| CliError::Other(error.to_string()))?;
    if contents.lines().any(|line| {
        let line = line.trim();
        line == "pub mod i18n;" || line == "mod i18n;"
    }) {
        return Ok(());
    }

    let mut updated = contents;
    if !updated.ends_with('\n') {
        updated.push('\n');
    }
    updated.push_str("pub mod i18n;\n");
    if dry_run {
        println!("Would update {}", path.display());
        return Ok(());
    }
    fs::write(path, updated).map_err(|error| CliError::Other(error.to_string()))
}

fn update_cargo_toml(
    root: &Path,
    manager: InitManager,
    build_rs: bool,
    dry_run: bool,
) -> Result<(), CliError> {
    let path = root.join("Cargo.toml");
    let mut manifest =
        fs::read_to_string(&path).map_err(|error| CliError::Other(error.to_string()))?;
    let original = manifest.clone();
    let version = env!("CARGO_PKG_VERSION");

    ensure_manifest_dependency(
        &mut manifest,
        "dependencies",
        "es-fluent",
        &format!("\"{version}\""),
    );
    ensure_manifest_dependency(&mut manifest, "dependencies", "unic-langid", "\"0.9\"");
    let (manager_name, manager_spec) = manager_dependency(manager, version);
    ensure_manifest_dependency(&mut manifest, "dependencies", manager_name, &manager_spec);

    if build_rs {
        ensure_manifest_dependency(
            &mut manifest,
            "build-dependencies",
            "es-fluent",
            &format!("{{ version = \"{version}\", features = [\"build\"] }}"),
        );
    }

    if manifest == original {
        println!("Cargo.toml already has the requested es-fluent dependencies");
        return Ok(());
    }

    if dry_run {
        println!("Would update {}", path.display());
        return Ok(());
    }

    fs::write(path, manifest).map_err(|error| CliError::Other(error.to_string()))
}

fn manager_dependency(manager: InitManager, version: &str) -> (&'static str, String) {
    match manager {
        InitManager::Embedded => ("es-fluent-manager-embedded", format!("\"{version}\"")),
        InitManager::Dioxus => (
            "es-fluent-manager-dioxus",
            "{ version = \"0.7.0\", features = [\"client\"] }".to_string(),
        ),
        InitManager::Bevy => ("es-fluent-manager-bevy", "\"0.18.13\"".to_string()),
    }
}

fn ensure_manifest_dependency(
    manifest: &mut String,
    section: &str,
    name: &str,
    spec: &str,
) -> bool {
    if section_has_dependency(manifest, section, name) {
        return false;
    }

    let dependency = format!("{name} = {spec}\n");
    if let Some(index) = section_insert_index(manifest, section) {
        manifest.insert_str(index, &dependency);
    } else {
        if !manifest.ends_with('\n') {
            manifest.push('\n');
        }
        manifest.push_str(&format!("\n[{section}]\n{dependency}"));
    }

    true
}

fn section_has_dependency(manifest: &str, section: &str, name: &str) -> bool {
    let mut in_section = false;
    for line in manifest.lines() {
        let trimmed = line.trim();
        if trimmed.starts_with('[') && trimmed.ends_with(']') {
            in_section = trimmed == format!("[{section}]");
            continue;
        }

        if in_section
            && (trimmed.starts_with(&format!("{name} ="))
                || trimmed.starts_with(&format!("{name}=")))
        {
            return true;
        }
    }

    false
}

fn section_insert_index(manifest: &str, section: &str) -> Option<usize> {
    let section_header = format!("[{section}]");
    let mut in_section = false;
    let mut last_index = None;

    for (index, line) in manifest.split_inclusive('\n').enumerate() {
        let byte_index = manifest
            .split_inclusive('\n')
            .take(index)
            .map(str::len)
            .sum::<usize>();
        let trimmed = line.trim();
        if trimmed.starts_with('[') && trimmed.ends_with(']') {
            if in_section {
                return Some(byte_index);
            }
            in_section = trimmed == section_header;
        }
        if in_section {
            last_index = Some(byte_index + line.len());
        }
    }

    last_index
}
