//! Init command implementation.
use crate::core::CliError;
use clap::{Parser, ValueEnum};
use es_fluent_shared::namespace::validate_namespace_path;
use fs_err as fs;
use std::collections::BTreeSet;
use std::path::{Path, PathBuf};
use toml_edit::{Array, DocumentMut, InlineTable, Item, TableLike, Value, value};

/// Runtime manager scaffold generated by `cargo es-fluent init`.
#[derive(Clone, Copy, Debug, Eq, PartialEq, ValueEnum)]
pub enum InitManager {
    /// Standard Rust applications using embedded FTL assets.
    Embedded,
    /// Dioxus client or SSR applications.
    Dioxus,
    /// Bevy applications using Bevy's AssetServer.
    Bevy,
}

impl InitManager {
    fn module_contents(self) -> &'static str {
        match self {
            Self::Embedded => {
                r#"//! es-fluent embedded runtime setup.

pub use es_fluent_manager_embedded::{
    EmbeddedI18n as I18n, EmbeddedInitError, LocalizationError,
};

es_fluent_manager_embedded::define_i18n_module!();
"#
            },
            Self::Dioxus => {
                r#"//! es-fluent Dioxus runtime setup.

pub use es_fluent_manager_dioxus::*;

es_fluent_manager_dioxus::define_i18n_module!();
"#
            },
            Self::Bevy => {
                r#"//! es-fluent Bevy runtime setup.

pub use es_fluent_manager_bevy::*;

es_fluent_manager_bevy::define_i18n_module!();
"#
            },
        }
    }
}

/// Dioxus runtime features to add when scaffolding the Dioxus manager.
#[derive(Clone, Copy, Debug, Eq, Ord, PartialEq, PartialOrd, ValueEnum)]
pub enum InitDioxusRuntime {
    /// Dioxus provider, hooks, and client-side locale state.
    Client,
    /// Request-scoped Dioxus SSR localization.
    Ssr,
}

impl InitDioxusRuntime {
    fn feature(self) -> &'static str {
        match self {
            Self::Client => "client",
            Self::Ssr => "ssr",
        }
    }
}

/// Arguments for the init command.
#[derive(Debug, Parser)]
pub struct InitArgs {
    /// Path to the crate root to initialize (defaults to current directory).
    #[arg(short, long)]
    pub path: Option<PathBuf>,

    /// Fallback locale to write into i18n.toml and create under assets_dir.
    #[arg(long, default_value = "en")]
    pub fallback_language: String,

    /// Additional locale directories to create.
    #[arg(long, value_delimiter = ',')]
    pub locales: Vec<String>,

    /// Locale asset directory relative to the crate root.
    #[arg(long, default_value = "assets/locales")]
    pub assets_dir: PathBuf,

    /// Namespace allowlist to write into i18n.toml.
    #[arg(long, value_delimiter = ',')]
    pub namespaces: Vec<String>,

    /// Runtime manager to scaffold.
    #[arg(long, value_enum, default_value = "embedded")]
    pub manager: InitManager,

    /// Dioxus dependency features for --manager dioxus with --update-cargo-toml.
    /// Omit to enable client and ssr.
    #[arg(long, value_enum, value_delimiter = ',')]
    pub dioxus_runtime: Vec<InitDioxusRuntime>,

    /// Also create a build.rs that tracks locale asset changes.
    #[arg(long)]
    pub build_rs: bool,

    /// Also add the matching runtime dependencies to Cargo.toml.
    #[arg(long)]
    pub update_cargo_toml: bool,

    /// Dry run - show what would be created without making changes.
    #[arg(long)]
    pub dry_run: bool,

    /// Overwrite existing generated files when they already exist.
    #[arg(long)]
    pub force: bool,
}

/// Run the init command.
pub fn run_init(args: InitArgs) -> Result<(), CliError> {
    let root = args.path.clone().unwrap_or_else(|| PathBuf::from("."));
    if !root.exists() {
        return Err(CliError::Other(format!(
            "crate root does not exist: {}",
            root.display()
        )));
    }
    if !root.is_dir() {
        return Err(CliError::Other(format!(
            "crate root is not a directory: {}",
            root.display()
        )));
    }
    if args.manager != InitManager::Dioxus && !args.dioxus_runtime.is_empty() {
        return Err(CliError::Other(
            "--dioxus-runtime can only be used with --manager dioxus".to_string(),
        ));
    }

    let fallback_language = crate::commands::sync::canonical_locale(&args.fallback_language)?;
    let mut locales = BTreeSet::from([fallback_language.clone()]);
    for locale in &args.locales {
        locales.insert(crate::commands::sync::canonical_locale(locale)?);
    }

    let assets_dir_toml = args.assets_dir.to_string_lossy().replace('\\', "/");
    let namespaces = validate_init_namespaces(&args.namespaces)?;
    let config = init_config_toml(&fallback_language, &assets_dir_toml, &namespaces)?;
    let preflight = preflight_init(&root, &args, &locales)?;

    write_new_file(&root.join("i18n.toml"), &config, args.force, args.dry_run)?;

    for locale in &locales {
        create_dir_all(&root.join(&args.assets_dir).join(locale), args.dry_run)?;
    }

    let src_dir = root.join("src");
    create_dir_all(&src_dir, args.dry_run)?;

    write_new_file(
        &src_dir.join("i18n.rs"),
        args.manager.module_contents(),
        args.force,
        args.dry_run,
    )?;

    let lib_path = src_dir.join("lib.rs");
    ensure_lib_declares_i18n_module(&lib_path, args.force, args.dry_run)?;

    if args.build_rs {
        write_new_file(
            &root.join("build.rs"),
            "fn main() {\n    es_fluent::build::track_i18n_assets();\n}\n",
            args.force,
            args.dry_run,
        )?;
    }

    if args.update_cargo_toml {
        update_cargo_toml(
            &root,
            args.manager,
            &args.dioxus_runtime,
            args.build_rs,
            args.dry_run,
        )?;
    }

    if args.dry_run {
        println!("Dry run complete for {}", root.display());
    } else {
        println!("Initialized es-fluent project at {}", root.display());
    }
    if preflight.created_library_target && preflight.has_binary_target {
        let action = if args.dry_run {
            "would create"
        } else {
            "created"
        };
        println!(
            "Note: init {action} src/lib.rs because derive inventory collection reads library targets. Put derived message types in src/lib.rs or another library crate; binary-only derived types in src/main.rs are not discovered by generate."
        );
    }
    if args.update_cargo_toml {
        if args.dry_run {
            println!("Cargo.toml dependency updates were included in the dry-run preview.");
        } else {
            println!("Cargo.toml dependencies were added or already present.");
        }
        println!("Next: derive EsFluent types, then run `cargo es-fluent generate`.");
    } else {
        println!(
            "Next: add the matching manager crate to Cargo.toml, derive EsFluent types, then run `cargo es-fluent generate`."
        );
        if args.build_rs {
            println!(
                "Also add `es-fluent = {{ version = \"{}\", features = [\"build\"] }}` under [build-dependencies].",
                env!("CARGO_PKG_VERSION")
            );
        }
    }

    Ok(())
}

struct InitPreflight {
    created_library_target: bool,
    has_binary_target: bool,
}

fn preflight_init(
    root: &Path,
    args: &InitArgs,
    locales: &BTreeSet<String>,
) -> Result<InitPreflight, CliError> {
    let src_dir = root.join("src");
    let lib_path = src_dir.join("lib.rs");
    let created_library_target = !lib_path.exists();
    let has_binary_target = src_dir.join("main.rs").exists();

    preflight_new_file(&root.join("i18n.toml"), args.force)?;
    for locale in locales {
        preflight_create_dir_all(&root.join(&args.assets_dir).join(locale))?;
    }
    preflight_create_dir_all(&src_dir)?;
    preflight_new_file(&src_dir.join("i18n.rs"), args.force)?;
    preflight_lib_update(&lib_path)?;

    if args.build_rs {
        preflight_new_file(&root.join("build.rs"), args.force)?;
    }

    if args.update_cargo_toml {
        prepare_cargo_toml_update(root, args.manager, &args.dioxus_runtime, args.build_rs)?;
    }

    Ok(InitPreflight {
        created_library_target,
        has_binary_target,
    })
}

fn preflight_new_file(path: &Path, force: bool) -> Result<(), CliError> {
    if path.is_dir() {
        return Err(CliError::Other(format!(
            "{} is a directory; expected a file path",
            path.display()
        )));
    }
    if path.exists() && !force {
        return Err(CliError::Other(format!(
            "{} already exists; pass --force to overwrite it",
            path.display()
        )));
    }

    Ok(())
}

fn preflight_create_dir_all(path: &Path) -> Result<(), CliError> {
    for candidate in path.ancestors() {
        if candidate.as_os_str().is_empty() {
            continue;
        }
        if candidate.exists() && !candidate.is_dir() {
            return Err(CliError::Other(format!(
                "cannot create directory {} because {} is not a directory",
                path.display(),
                candidate.display()
            )));
        }
    }

    Ok(())
}

fn preflight_lib_update(path: &Path) -> Result<(), CliError> {
    if path.exists() {
        fs::read_to_string(path).map_err(|error| CliError::Other(error.to_string()))?;
    }

    Ok(())
}

fn validate_init_namespaces(namespaces: &[String]) -> Result<Vec<String>, CliError> {
    for namespace in namespaces {
        validate_namespace_path(namespace).map_err(|reason| {
            CliError::Other(format!("invalid namespace '{}': {}", namespace, reason))
        })?;
    }

    Ok(namespaces.to_vec())
}

fn init_config_toml(
    fallback_language: &str,
    assets_dir: &str,
    namespaces: &[String],
) -> Result<String, CliError> {
    let mut config = toml::Table::new();
    config.insert(
        "fallback_language".to_string(),
        toml::Value::String(fallback_language.to_string()),
    );
    config.insert(
        "assets_dir".to_string(),
        toml::Value::String(assets_dir.to_string()),
    );
    if !namespaces.is_empty() {
        config.insert(
            "namespaces".to_string(),
            toml::Value::Array(
                namespaces
                    .iter()
                    .map(|namespace| toml::Value::String(namespace.clone()))
                    .collect(),
            ),
        );
    }

    toml::to_string(&config)
        .map_err(|error| CliError::Other(format!("failed to serialize i18n.toml: {error}")))
}

fn create_dir_all(path: &Path, dry_run: bool) -> Result<(), CliError> {
    if dry_run {
        println!("Would create directory {}", path.display());
        return Ok(());
    }

    fs::create_dir_all(path).map_err(|error| CliError::Other(error.to_string()))
}

fn write_new_file(path: &Path, contents: &str, force: bool, dry_run: bool) -> Result<(), CliError> {
    if path.exists() && !force {
        return Err(CliError::Other(format!(
            "{} already exists; pass --force to overwrite it",
            path.display()
        )));
    }

    if dry_run {
        println!("Would write {}", path.display());
        return Ok(());
    }

    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).map_err(|error| CliError::Other(error.to_string()))?;
    }
    fs::write(path, contents).map_err(|error| CliError::Other(error.to_string()))
}

fn ensure_lib_declares_i18n_module(
    path: &Path,
    force: bool,
    dry_run: bool,
) -> Result<(), CliError> {
    if !path.exists() {
        return write_new_file(path, "pub mod i18n;\n", force, dry_run);
    }

    let contents = fs::read_to_string(path).map_err(|error| CliError::Other(error.to_string()))?;
    if contents.lines().any(|line| {
        let line = line.trim();
        line == "pub mod i18n;" || line == "mod i18n;"
    }) {
        return Ok(());
    }

    let mut updated = contents;
    if !updated.ends_with('\n') {
        updated.push('\n');
    }
    updated.push_str("pub mod i18n;\n");
    if dry_run {
        println!("Would update {}", path.display());
        return Ok(());
    }
    fs::write(path, updated).map_err(|error| CliError::Other(error.to_string()))
}

fn update_cargo_toml(
    root: &Path,
    manager: InitManager,
    dioxus_runtime: &[InitDioxusRuntime],
    build_rs: bool,
    dry_run: bool,
) -> Result<(), CliError> {
    let Some((path, manifest)) =
        prepare_cargo_toml_update(root, manager, dioxus_runtime, build_rs)?
    else {
        println!("Cargo.toml already has the requested es-fluent dependencies");
        return Ok(());
    };

    if dry_run {
        println!("Would update {}", path.display());
        return Ok(());
    }

    fs::write(path, manifest).map_err(|error| CliError::Other(error.to_string()))
}

fn prepare_cargo_toml_update(
    root: &Path,
    manager: InitManager,
    dioxus_runtime: &[InitDioxusRuntime],
    build_rs: bool,
) -> Result<Option<(PathBuf, String)>, CliError> {
    let path = root.join("Cargo.toml");
    let manifest = fs::read_to_string(&path).map_err(|error| CliError::Other(error.to_string()))?;
    let original = manifest.clone();
    let mut manifest = manifest
        .parse::<DocumentMut>()
        .map_err(|error| CliError::Other(format!("failed to parse Cargo.toml: {error}")))?;
    let version = env!("CARGO_PKG_VERSION");

    ensure_manifest_dependency(
        &mut manifest,
        "dependencies",
        "es-fluent",
        version_dependency(version),
    )?;
    ensure_manifest_dependency(
        &mut manifest,
        "dependencies",
        "unic-langid",
        version_dependency("0.9"),
    )?;
    let (manager_name, manager_spec) = manager_dependency(manager, version, dioxus_runtime);
    ensure_manifest_dependency(&mut manifest, "dependencies", manager_name, manager_spec)?;

    if build_rs {
        ensure_manifest_dependency(
            &mut manifest,
            "build-dependencies",
            "es-fluent",
            dependency_with_features(version, &["build"]),
        )?;
        ensure_manifest_dependency_feature(
            &mut manifest,
            "build-dependencies",
            "es-fluent",
            "build",
        )?;
    }

    let manifest = manifest.to_string();
    if manifest == original {
        Ok(None)
    } else {
        Ok(Some((path, manifest)))
    }
}

fn manager_dependency(
    manager: InitManager,
    version: &str,
    dioxus_runtime: &[InitDioxusRuntime],
) -> (&'static str, Item) {
    match manager {
        InitManager::Embedded => ("es-fluent-manager-embedded", version_dependency(version)),
        InitManager::Dioxus => (
            "es-fluent-manager-dioxus",
            dependency_with_features("0.7.0", &dioxus_runtime_features(dioxus_runtime)),
        ),
        InitManager::Bevy => ("es-fluent-manager-bevy", version_dependency("0.18.13")),
    }
}

fn dioxus_runtime_features(dioxus_runtime: &[InitDioxusRuntime]) -> Vec<&'static str> {
    let selected = if dioxus_runtime.is_empty() {
        BTreeSet::from([InitDioxusRuntime::Client, InitDioxusRuntime::Ssr])
    } else {
        dioxus_runtime.iter().copied().collect::<BTreeSet<_>>()
    };

    selected
        .into_iter()
        .map(InitDioxusRuntime::feature)
        .collect()
}

fn ensure_manifest_dependency(
    manifest: &mut DocumentMut,
    section: &str,
    name: &str,
    spec: Item,
) -> Result<bool, CliError> {
    if section_has_dependency(manifest, section, name) {
        return Ok(false);
    }

    if manifest.as_table().get(section).is_none() {
        manifest.as_table_mut().insert(section, toml_edit::table());
    }

    let section = manifest
        .as_table_mut()
        .get_mut(section)
        .and_then(Item::as_table_like_mut)
        .ok_or_else(|| CliError::Other(format!("Cargo.toml [{section}] is not a table")))?;
    section.insert(name, spec);

    Ok(true)
}

fn section_has_dependency(manifest: &DocumentMut, section: &str, name: &str) -> bool {
    manifest
        .as_table()
        .get(section)
        .and_then(Item::as_table_like)
        .is_some_and(|section| section.contains_key(name))
}

fn ensure_manifest_dependency_feature(
    manifest: &mut DocumentMut,
    section: &str,
    name: &str,
    feature: &str,
) -> Result<bool, CliError> {
    let section_table = manifest
        .as_table_mut()
        .get_mut(section)
        .and_then(Item::as_table_like_mut)
        .ok_or_else(|| CliError::Other(format!("Cargo.toml [{section}] is not a table")))?;
    let dependency = section_table
        .get_mut(name)
        .ok_or_else(|| CliError::Other(format!("Cargo.toml [{section}] is missing {name}")))?;

    if let Some(dependency) = dependency.as_table_like_mut() {
        return ensure_table_like_dependency_feature(dependency, feature);
    }

    if let Some(version) = dependency
        .as_value()
        .and_then(Value::as_str)
        .map(str::to_owned)
    {
        let mut table = InlineTable::new();
        table.insert("version", Value::from(version));
        insert_dependency_features(&mut table, &[feature]);
        table.fmt();
        *dependency = value(table);
        return Ok(true);
    }

    Err(CliError::Other(format!(
        "Cargo.toml [{section}] dependency {name} must be a version string or table to enable feature {feature:?}"
    )))
}

fn ensure_table_like_dependency_feature(
    dependency: &mut dyn TableLike,
    feature: &str,
) -> Result<bool, CliError> {
    if let Some(features) = dependency.get_mut("features") {
        let features = features
            .as_value_mut()
            .and_then(Value::as_array_mut)
            .ok_or_else(|| {
                CliError::Other(
                    "Cargo.toml es-fluent dependency features must be an array".to_string(),
                )
            })?;

        if features
            .iter()
            .any(|existing| existing.as_str() == Some(feature))
        {
            return Ok(false);
        }

        features.push(feature);
        features.fmt();
        return Ok(true);
    }

    let mut features = Array::new();
    features.push(feature);
    features.fmt();
    dependency.insert("features", value(features));
    Ok(true)
}

fn insert_dependency_features(table: &mut InlineTable, features: &[&str]) {
    let mut feature_values = Array::new();
    for feature in features {
        feature_values.push(*feature);
    }
    feature_values.fmt();
    table.insert("features", Value::from(feature_values));
}

fn version_dependency(version: &str) -> Item {
    value(version)
}

fn dependency_with_features(version: &str, features: &[&str]) -> Item {
    let mut dependency = InlineTable::new();
    dependency.insert("version", Value::from(version));
    insert_dependency_features(&mut dependency, features);
    dependency.fmt();

    value(dependency)
}

#[cfg(test)]
mod tests {
    use super::*;
    use fs_err as test_fs;
    use std::sync::atomic::{AtomicUsize, Ordering};

    static NEXT_ID: AtomicUsize = AtomicUsize::new(0);

    struct TempProject {
        root: PathBuf,
    }

    impl TempProject {
        fn new(name: &str, with_manifest: bool) -> Self {
            let id = NEXT_ID.fetch_add(1, Ordering::Relaxed);
            let root = std::env::temp_dir().join(format!(
                "es_fluent_init_{name}_{}_{}",
                std::process::id(),
                id
            ));
            let _ = test_fs::remove_dir_all(&root);
            test_fs::create_dir_all(&root).expect("temp project root should be created");

            if with_manifest {
                test_fs::write(
                    root.join("Cargo.toml"),
                    "[package]\nname = \"init-test\"\nversion = \"0.1.0\"\nedition = \"2021\"\n",
                )
                .expect("temp manifest should be written");
            }

            Self { root }
        }

        fn path(&self) -> &Path {
            &self.root
        }
    }

    impl Drop for TempProject {
        fn drop(&mut self) {
            let _ = test_fs::remove_dir_all(&self.root);
        }
    }

    fn default_args(root: &Path) -> InitArgs {
        InitArgs {
            path: Some(root.to_path_buf()),
            fallback_language: "en".to_string(),
            locales: Vec::new(),
            assets_dir: PathBuf::from("assets/locales"),
            namespaces: Vec::new(),
            manager: InitManager::Embedded,
            dioxus_runtime: Vec::new(),
            build_rs: false,
            update_cargo_toml: false,
            dry_run: false,
            force: false,
        }
    }

    fn write_manifest(root: &Path, manifest: &str) {
        test_fs::write(root.join("Cargo.toml"), manifest).expect("temp manifest should be written");
    }

    #[test]
    fn init_manager_module_contents_match_selected_runtime() {
        assert!(
            InitManager::Embedded
                .module_contents()
                .contains("es_fluent_manager_embedded::define_i18n_module!();")
        );
        assert!(
            InitManager::Dioxus
                .module_contents()
                .contains("es_fluent_manager_dioxus::define_i18n_module!();")
        );
        assert!(
            InitManager::Bevy
                .module_contents()
                .contains("es_fluent_manager_bevy::define_i18n_module!();")
        );
    }

    #[test]
    fn run_init_creates_project_scaffold_and_updates_manifest() {
        let project = TempProject::new("scaffold", true);
        let mut args = default_args(project.path());
        args.fallback_language = "en-US".to_string();
        args.locales = vec!["fr".to_string(), "de".to_string(), "en-US".to_string()];
        args.assets_dir = PathBuf::from("i18n");
        args.namespaces = vec!["auth".to_string(), "ui".to_string()];
        args.manager = InitManager::Dioxus;
        args.build_rs = true;
        args.update_cargo_toml = true;

        run_init(args).expect("init should scaffold the project");

        let config = test_fs::read_to_string(project.path().join("i18n.toml"))
            .expect("i18n.toml should exist");
        assert!(config.contains("fallback_language = \"en-US\""));
        assert!(config.contains("assets_dir = \"i18n\""));
        assert!(config.contains("namespaces = [\"auth\", \"ui\"]"));

        assert!(project.path().join("i18n/en-US").is_dir());
        assert!(project.path().join("i18n/fr").is_dir());
        assert!(project.path().join("i18n/de").is_dir());

        let module = test_fs::read_to_string(project.path().join("src/i18n.rs"))
            .expect("runtime module should exist");
        assert!(module.contains("pub use es_fluent_manager_dioxus::*;"));
        assert!(module.contains("define_i18n_module"));

        let lib = test_fs::read_to_string(project.path().join("src/lib.rs"))
            .expect("lib.rs should be created");
        assert_eq!(lib, "pub mod i18n;\n");

        let build_rs = test_fs::read_to_string(project.path().join("build.rs"))
            .expect("build.rs should be created");
        assert!(build_rs.contains("es_fluent::build::track_i18n_assets"));

        let manifest = test_fs::read_to_string(project.path().join("Cargo.toml"))
            .expect("manifest should be updated");
        assert!(manifest.contains("es-fluent"));
        assert!(manifest.contains("unic-langid"));
        assert!(manifest.contains("es-fluent-manager-dioxus"));
        assert!(manifest.contains("features = [\"client\", \"ssr\"]"));
        assert!(manifest.contains("[build-dependencies]"));
    }

    #[test]
    fn run_init_updates_dioxus_manifest_for_selected_runtimes() {
        let cases = [
            (
                "dioxus_client",
                vec![InitDioxusRuntime::Client],
                "es-fluent-manager-dioxus = { version = \"0.7.0\", features = [\"client\"] }",
            ),
            (
                "dioxus_ssr",
                vec![InitDioxusRuntime::Ssr],
                "es-fluent-manager-dioxus = { version = \"0.7.0\", features = [\"ssr\"] }",
            ),
            (
                "dioxus_both",
                vec![InitDioxusRuntime::Ssr, InitDioxusRuntime::Client],
                "es-fluent-manager-dioxus = { version = \"0.7.0\", features = [\"client\", \"ssr\"] }",
            ),
            (
                "dioxus_default",
                Vec::new(),
                "es-fluent-manager-dioxus = { version = \"0.7.0\", features = [\"client\", \"ssr\"] }",
            ),
        ];

        for (name, dioxus_runtime, expected_dependency) in cases {
            let project = TempProject::new(name, true);
            let mut args = default_args(project.path());
            args.manager = InitManager::Dioxus;
            args.dioxus_runtime = dioxus_runtime;
            args.update_cargo_toml = true;

            run_init(args).expect("init should update the Dioxus manifest dependency");

            let manifest = test_fs::read_to_string(project.path().join("Cargo.toml"))
                .expect("manifest should be updated");
            assert!(manifest.contains(expected_dependency));
        }
    }

    #[test]
    fn run_init_manifest_update_recognizes_table_form_dependencies() {
        let project = TempProject::new("table_form_dependencies", false);
        write_manifest(
            project.path(),
            r#"[package]
name = "init-test"
version = "0.1.0"
edition = "2021"

[dependencies]
unic-langid = "0.9"
es-fluent-manager-embedded = "0.16"

[dependencies.es-fluent]
version = "0.16"
features = ["derive"]
"#,
        );
        let mut args = default_args(project.path());
        args.update_cargo_toml = true;

        run_init(args).expect("table-form dependencies should be detected as present");

        let manifest = test_fs::read_to_string(project.path().join("Cargo.toml"))
            .expect("manifest should remain valid");
        assert!(manifest.contains("[dependencies.es-fluent]"));
        assert_eq!(manifest.matches("\nes-fluent =").count(), 0);
        assert_eq!(
            manifest.matches("\nes-fluent-manager-embedded =").count(),
            1
        );
    }

    #[test]
    fn run_init_manifest_update_recognizes_workspace_dependencies() {
        let project = TempProject::new("workspace_dependencies", false);
        write_manifest(
            project.path(),
            r#"[package]
name = "init-test"
version = "0.1.0"
edition = "2021"

[dependencies]
es-fluent.workspace = true
unic-langid.workspace = true
es-fluent-manager-embedded.workspace = true
"#,
        );
        let mut args = default_args(project.path());
        args.update_cargo_toml = true;

        run_init(args).expect("workspace dependencies should be detected as present");

        let manifest = test_fs::read_to_string(project.path().join("Cargo.toml"))
            .expect("manifest should remain valid");
        assert!(manifest.contains("es-fluent.workspace = true"));
        assert!(manifest.contains("unic-langid.workspace = true"));
        assert!(manifest.contains("es-fluent-manager-embedded.workspace = true"));
        assert_eq!(manifest.matches("\nes-fluent =").count(), 0);
        assert_eq!(manifest.matches("\nunic-langid =").count(), 0);
        assert_eq!(
            manifest.matches("\nes-fluent-manager-embedded =").count(),
            0
        );
    }

    #[test]
    fn run_init_manifest_update_preserves_existing_manager_features() {
        let project = TempProject::new("manager_features", false);
        write_manifest(
            project.path(),
            r#"[package]
name = "init-test"
version = "0.1.0"
edition = "2021"

[dependencies]
es-fluent = "0.16"
unic-langid = "0.9"
es-fluent-manager-dioxus = { version = "0.7", features = ["client"] }
"#,
        );
        let mut args = default_args(project.path());
        args.manager = InitManager::Dioxus;
        args.update_cargo_toml = true;

        run_init(args).expect("existing Dioxus manager dependency should be left unchanged");

        let manifest = test_fs::read_to_string(project.path().join("Cargo.toml"))
            .expect("manifest should remain valid");
        assert!(
            manifest.contains(
                r#"es-fluent-manager-dioxus = { version = "0.7", features = ["client"] }"#
            )
        );
        assert_eq!(manifest.matches("\nes-fluent-manager-dioxus =").count(), 1);
        assert!(!manifest.contains(r#"features = ["client", "ssr"]"#));
    }

    #[test]
    fn run_init_manifest_update_adds_build_feature_to_existing_build_dependency() {
        for (name, build_dependency, expected_features) in [
            ("string", r#"es-fluent = "0.16""#, BTreeSet::from(["build"])),
            (
                "feature_merge",
                r#"es-fluent = { version = "0.16", features = ["derive"] }"#,
                BTreeSet::from(["build", "derive"]),
            ),
        ] {
            let project = TempProject::new(name, false);
            write_manifest(
                project.path(),
                &format!(
                    r#"[package]
name = "init-test"
version = "0.1.0"
edition = "2021"

[dependencies]
es-fluent = "0.16"
unic-langid = "0.9"
es-fluent-manager-embedded = "0.16"

[build-dependencies]
{build_dependency}
"#
                ),
            );
            let mut args = default_args(project.path());
            args.build_rs = true;
            args.update_cargo_toml = true;

            run_init(args).expect("existing build dependency should gain the build feature");

            let manifest = test_fs::read_to_string(project.path().join("Cargo.toml"))
                .expect("manifest should be updated");
            let parsed =
                toml::from_str::<toml::Value>(&manifest).expect("updated manifest should parse");
            let features = parsed
                .get("build-dependencies")
                .and_then(|deps| deps.get("es-fluent"))
                .and_then(|dep| dep.get("features"))
                .and_then(toml::Value::as_array)
                .expect("build dependency should have features");
            let features = features
                .iter()
                .filter_map(toml::Value::as_str)
                .collect::<BTreeSet<_>>();

            assert_eq!(features, expected_features);
            assert_eq!(manifest.matches("\nes-fluent =").count(), 2);
        }
    }

    #[test]
    fn run_init_rejects_dioxus_runtime_without_dioxus_manager() {
        let project = TempProject::new("dioxus_runtime_without_manager", true);
        let mut args = default_args(project.path());
        args.dioxus_runtime = vec![InitDioxusRuntime::Ssr];

        let err = run_init(args).expect_err("--dioxus-runtime should require the Dioxus manager");

        assert!(
            err.to_string()
                .contains("--dioxus-runtime can only be used with --manager dioxus")
        );
    }

    #[test]
    fn run_init_rejects_invalid_namespaces() {
        for (name, namespace) in [
            ("backslash", r"ui\button"),
            ("traversal", "../escape"),
            ("empty_segment", "ui//button"),
            ("empty", ""),
        ] {
            let project = TempProject::new(name, false);
            let mut args = default_args(project.path());
            args.namespaces = vec![namespace.to_string()];

            let err = run_init(args).expect_err("invalid namespace should be rejected");

            assert!(err.to_string().contains("invalid namespace"));
            assert!(!project.path().join("i18n.toml").exists());
        }
    }

    #[test]
    fn run_init_serializes_namespace_allowlist_with_toml_escaping() {
        let project = TempProject::new("namespace_escaping", false);
        let mut args = default_args(project.path());
        args.namespaces = vec![r#"ui"quote"#.to_string()];

        run_init(args).expect("namespace requiring TOML escaping should be serialized");

        let config =
            test_fs::read_to_string(project.path().join("i18n.toml")).expect("read config");
        let parsed =
            toml::from_str::<toml::Table>(&config).expect("generated config should be valid TOML");
        let namespaces = parsed
            .get("namespaces")
            .and_then(toml::Value::as_array)
            .expect("namespaces should be present");
        assert_eq!(namespaces[0].as_str(), Some(r#"ui"quote"#));
    }

    #[test]
    fn run_init_preflights_file_conflicts_before_writing() {
        let project = TempProject::new("preflight_conflict", false);
        test_fs::create_dir_all(project.path().join("src")).expect("src should be created");
        test_fs::write(project.path().join("src/i18n.rs"), "existing module\n")
            .expect("existing generated module should be written");

        let err = run_init(default_args(project.path()))
            .expect_err("existing generated module should be rejected");

        assert!(err.to_string().contains("pass --force to overwrite"));
        assert!(!project.path().join("i18n.toml").exists());
        assert!(!project.path().join("assets").exists());
        assert_eq!(
            test_fs::read_to_string(project.path().join("src/i18n.rs"))
                .expect("existing generated module should remain"),
            "existing module\n"
        );
    }

    #[test]
    fn run_init_appends_lib_module_once_and_respects_existing_decl() {
        let project = TempProject::new("lib_decl", false);
        test_fs::create_dir_all(project.path().join("src")).expect("src should be created");
        test_fs::write(project.path().join("src/lib.rs"), "pub fn existing() {}")
            .expect("lib.rs should be seeded");

        let mut args = default_args(project.path());
        args.force = true;
        run_init(args).expect("init should append the i18n module declaration");

        let lib = test_fs::read_to_string(project.path().join("src/lib.rs"))
            .expect("lib.rs should be readable");
        assert_eq!(lib, "pub fn existing() {}\npub mod i18n;\n");

        let mut args = default_args(project.path());
        args.force = true;
        run_init(args).expect("existing module declaration should be left alone");

        let lib = test_fs::read_to_string(project.path().join("src/lib.rs"))
            .expect("lib.rs should be readable");
        assert_eq!(
            lib.lines()
                .filter(|line| line.trim() == "pub mod i18n;")
                .count(),
            1
        );
    }

    #[test]
    fn run_init_dry_run_does_not_write_files_or_directories() {
        let project = TempProject::new("dry_run", false);
        let mut args = default_args(project.path());
        args.locales = vec!["fr".to_string()];
        args.manager = InitManager::Bevy;
        args.build_rs = true;
        args.dry_run = true;

        run_init(args).expect("dry-run init should succeed");

        assert!(!project.path().join("i18n.toml").exists());
        assert!(!project.path().join("src").exists());
        assert!(!project.path().join("assets").exists());
        assert!(!project.path().join("build.rs").exists());
    }

    #[test]
    fn run_init_rejects_missing_or_file_roots() {
        let project = TempProject::new("bad_roots", false);
        let mut args = default_args(&project.path().join("missing"));
        let missing = run_init(args).expect_err("missing roots should be rejected");
        assert!(missing.to_string().contains("does not exist"));

        let file_root = project.path().join("not-a-directory");
        test_fs::write(&file_root, "not a directory").expect("file root should be written");
        args = default_args(&file_root);
        let file = run_init(args).expect_err("file roots should be rejected");
        assert!(file.to_string().contains("not a directory"));
    }

    #[test]
    fn run_init_refuses_to_overwrite_without_force_and_allows_force() {
        let project = TempProject::new("overwrite", false);
        test_fs::write(project.path().join("i18n.toml"), "existing = true\n")
            .expect("existing config should be written");

        let err = run_init(default_args(project.path()))
            .expect_err("existing generated files should require --force");
        assert!(err.to_string().contains("pass --force to overwrite"));
        assert_eq!(
            test_fs::read_to_string(project.path().join("i18n.toml"))
                .expect("existing config should remain"),
            "existing = true\n"
        );

        let mut args = default_args(project.path());
        args.force = true;
        run_init(args).expect("force should overwrite generated files");
        assert!(
            test_fs::read_to_string(project.path().join("i18n.toml"))
                .expect("config should be overwritten")
                .contains("fallback_language = \"en\"")
        );
    }

    #[test]
    fn run_init_reports_manifest_update_errors() {
        let project = TempProject::new("missing_manifest", false);
        let mut args = default_args(project.path());
        args.update_cargo_toml = true;

        let err = run_init(args).expect_err("missing Cargo.toml should fail manifest update");
        assert!(!err.to_string().is_empty());
        assert!(!project.path().join("i18n.toml").exists());
        assert!(!project.path().join("src").exists());
        assert!(!project.path().join("assets").exists());
    }
}
