//! Init command implementation.

use crate::core::CliError;
use clap::{Parser, ValueEnum};
use fs_err as fs;
use std::path::{Path, PathBuf};

/// Runtime manager scaffold generated by `cargo es-fluent init`.
#[derive(Clone, Copy, Debug, Eq, PartialEq, ValueEnum)]
pub enum InitManager {
    /// Standard Rust applications using embedded FTL assets.
    Embedded,
    /// Dioxus client or SSR applications.
    Dioxus,
    /// Bevy applications using Bevy's AssetServer.
    Bevy,
}

impl InitManager {
    fn module_contents(self) -> &'static str {
        match self {
            Self::Embedded => {
                r#"//! es-fluent embedded runtime setup.

pub use es_fluent_manager_embedded::{
    EmbeddedI18n as I18n, EmbeddedInitError, LocalizationError,
};

es_fluent_manager_embedded::define_i18n_module!();
"#
            },
            Self::Dioxus => {
                r#"//! es-fluent Dioxus runtime setup.

pub use es_fluent_manager_dioxus::*;

es_fluent_manager_dioxus::define_i18n_module!();
"#
            },
            Self::Bevy => {
                r#"//! es-fluent Bevy runtime setup.

pub use es_fluent_manager_bevy::*;

es_fluent_manager_bevy::define_i18n_module!();
"#
            },
        }
    }
}

/// Arguments for the init command.
#[derive(Debug, Parser)]
pub struct InitArgs {
    /// Path to the crate root to initialize (defaults to current directory).
    #[arg(short, long)]
    pub path: Option<PathBuf>,

    /// Fallback locale to write into i18n.toml and create under assets_dir.
    #[arg(long, default_value = "en")]
    pub fallback_language: String,

    /// Locale asset directory relative to the crate root.
    #[arg(long, default_value = "assets/locales")]
    pub assets_dir: PathBuf,

    /// Runtime manager to scaffold.
    #[arg(long, value_enum, default_value = "embedded")]
    pub manager: InitManager,

    /// Also create a build.rs that tracks locale asset changes.
    #[arg(long)]
    pub build_rs: bool,

    /// Overwrite existing generated files when they already exist.
    #[arg(long)]
    pub force: bool,
}

/// Run the init command.
pub fn run_init(args: InitArgs) -> Result<(), CliError> {
    let root = args.path.unwrap_or_else(|| PathBuf::from("."));
    if !root.exists() {
        return Err(CliError::Other(format!(
            "crate root does not exist: {}",
            root.display()
        )));
    }
    if !root.is_dir() {
        return Err(CliError::Other(format!(
            "crate root is not a directory: {}",
            root.display()
        )));
    }

    let assets_dir_toml = args.assets_dir.to_string_lossy().replace('\\', "/");

    write_new_file(
        &root.join("i18n.toml"),
        &format!(
            "fallback_language = \"{}\"\nassets_dir = \"{}\"\n",
            args.fallback_language, assets_dir_toml
        ),
        args.force,
    )?;

    fs::create_dir_all(root.join(&args.assets_dir).join(&args.fallback_language))
        .map_err(|error| CliError::Other(error.to_string()))?;

    let src_dir = root.join("src");
    fs::create_dir_all(&src_dir).map_err(|error| CliError::Other(error.to_string()))?;

    write_new_file(
        &src_dir.join("i18n.rs"),
        args.manager.module_contents(),
        args.force,
    )?;

    ensure_lib_declares_i18n_module(&src_dir.join("lib.rs"), args.force)?;

    if args.build_rs {
        write_new_file(
            &root.join("build.rs"),
            "fn main() {\n    es_fluent::build::track_i18n_assets();\n}\n",
            args.force,
        )?;
    }

    println!("Initialized es-fluent project at {}", root.display());
    println!(
        "Next: add the matching manager crate to Cargo.toml, derive EsFluent types, then run `cargo es-fluent generate`."
    );
    if args.build_rs {
        println!(
            "Also add `es-fluent = {{ version = \"{}\", features = [\"build\"] }}` under [build-dependencies].",
            env!("CARGO_PKG_VERSION")
        );
    }

    Ok(())
}

fn write_new_file(path: &Path, contents: &str, force: bool) -> Result<(), CliError> {
    if path.exists() && !force {
        return Err(CliError::Other(format!(
            "{} already exists; pass --force to overwrite it",
            path.display()
        )));
    }

    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).map_err(|error| CliError::Other(error.to_string()))?;
    }
    fs::write(path, contents).map_err(|error| CliError::Other(error.to_string()))
}

fn ensure_lib_declares_i18n_module(path: &Path, force: bool) -> Result<(), CliError> {
    if !path.exists() {
        return write_new_file(path, "pub mod i18n;\n", force);
    }

    let contents = fs::read_to_string(path).map_err(|error| CliError::Other(error.to_string()))?;
    if contents.lines().any(|line| {
        let line = line.trim();
        line == "pub mod i18n;" || line == "mod i18n;"
    }) {
        return Ok(());
    }

    let mut updated = contents;
    if !updated.ends_with('\n') {
        updated.push('\n');
    }
    updated.push_str("pub mod i18n;\n");
    fs::write(path, updated).map_err(|error| CliError::Other(error.to_string()))
}
