[package]
name = "shared-lib"
version.workspace = true
edition.workspace = true
license = "Unlicense"
publish = false

[dependencies]
bevy = { workspace = true, optional = true }
es-fluent = { features = [ "derive" ], workspace = true }
strum = { features = [ "derive" ], workspace = true }
unic-langid = { workspace = true }
es-fluent-manager-bevy = { workspace = true, optional = true }
es-fluent-manager-singleton = { workspace = true, optional = true }
rust-embed = { workspace = true, optional = true }
gpui = { workspace = true, optional = true }

[build-dependencies]
es-fluent-build = { workspace = true }
log = { workspace = true }

[lints]
workspace = true

[features]
gpui = ["dep:gpui", "dep:rust-embed", "dep:es-fluent-manager-singleton"]
bevy = ["dep:bevy", "dep:es-fluent-manager-bevy"]
