codecov:
  require_ci_to_pass: true

# https://docs.codecov.com/docs/components
component_management:
  individual_components:
    - component_id: es-fluent
      name: "es-fluent"
      paths:
        - crates/es-fluent/**

    - component_id: es-fluent-cli
      name: "es-fluent-cli"
      paths:
        - crates/es-fluent-cli/**

    - component_id: es-fluent-cli-helpers
      name: "es-fluent-cli-helpers"
      paths:
        - crates/es-fluent-cli-helpers/**

    - component_id: es-fluent-derive
      name: "es-fluent-derive"
      paths:
        - crates/es-fluent-derive/**

    - component_id: es-fluent-derive-core
      name: "es-fluent-derive-core"
      paths:
        - crates/es-fluent-derive-core/**

    - component_id: es-fluent-manager-macros
      name: "es-fluent-manager-macros"
      paths:
        - crates/es-fluent-manager-macros/**

    - component_id: es-fluent-manager-core
      name: "es-fluent-manager-core"
      paths:
        - crates/es-fluent-manager-core/**

    - component_id: es-fluent-manager-bevy
      name: "es-fluent-manager-bevy"
      paths:
        - crates/es-fluent-manager-bevy/**

    - component_id: es-fluent-manager-embedded
      name: "es-fluent-manager-embedded"
      paths:
        - crates/es-fluent-manager-embedded/**

    - component_id: es-fluent-lang
      name: "es-fluent-lang"
      paths:
        - crates/es-fluent-lang/**

    - component_id: es-fluent-lang-macro
      name: "es-fluent-lang-macro"
      paths:
        - crates/es-fluent-lang-macro/**

    - component_id: es-fluent-toml
      name: "es-fluent-toml"
      paths:
        - crates/es-fluent-toml/**

    - component_id: es-fluent-generate
      name: "es-fluent-generate"
      paths:
        - crates/es-fluent-generate/**

    - component_id: xtask
      name: "xtask"
      paths:
        - xtask/**

coverage:
  precision: 2
  round: down
  range: "90...100"
  status:
    project:
      default:
        target: 90%
        threshold: 5%
    patch:
      default:
        target: 90%
        threshold: 5%
