[package]
name = "es-fluent-manager-dioxus"
edition.workspace = true
license.workspace = true
publish.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true
description = "A Dioxus web-native internationalization (i18n) manager that integrates es-fluent with Dioxus's asset system."

[dependencies]
dioxus = { features = [ "macro", "hooks", "signals" ], workspace = true }
es-fluent = { workspace = true }
es-fluent-manager-core = { workspace = true }
es-fluent-manager-macros = { optional = true, workspace = true }
fluent-bundle = { workspace = true }
inventory = { workspace = true }
log = { workspace = true }
serde = { features = [ "derive" ], workspace = true }
unic-langid = { workspace = true }

[features]
default = [ "macros" ]
desktop = [ "dioxus/desktop" ]
fullstack = [ "dioxus/fullstack" ]
macros = [ "es-fluent-manager-macros" ]
ssr = [ "dioxus/ssr" ]
web = [ "dioxus/web" ]

[lints]
workspace = true
