// generated by cargo xtask generate-lang-names

pub const SUPPORTED_LANGUAGE_KEYS: &[&str] = &[
    "ar", "ast", "ba", "bal-Latn", "bg", "br", "brx", "bs", "bs-Cyrl", "ca", "cs", "cv", "cy",
    "da", "de", "el", "en", "eo", "es", "et", "eu", "fa", "ff-Adlm", "fi", "fil", "fo", "fr", "fy",
    "ga", "gd", "gu", "he", "hi", "hr", "hu", "hy", "id", "it", "ja", "kgp", "kk", "kk-Arab", "kn",
    "ko", "ks", "ku", "lb", "lo", "lt", "lv", "mk", "ml", "mr", "ms", "mt", "my", "ne", "nl", "nn",
    "no", "or", "pl", "pt", "pt-PT", "rm", "ro", "ru", "sc", "sd", "shn", "sk", "sl", "so", "sr",
    "sr-Latn", "sv", "ta", "te", "th", "ti", "tr", "ug", "uk", "vec", "vi", "xnr", "yrl", "yrl-CO",
    "yrl-VE", "yue", "yue-Hans", "zh", "zh-HK", "zh-Hant", "zh-MO", "zu",
];
