[package]
name = "dioxus-example"
edition.workspace = true
license.workspace = true
publish.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
dioxus = { version = "0.6.3", features = ["router", "fullstack"] }
dioxus-i18n = "0.4.3"
es-fluent = { features = [ "derive" ], workspace = true }
es-fluent-macros = { workspace = true }
fluent = { workspace = true }
fluent-bundle = { workspace = true }
inventory = { workspace = true }
log = { workspace = true }
rust-embed = { workspace = true }
strum = { features = [ "derive" ], workspace = true }
unic-langid = { workspace = true }

[build-dependencies]
es-fluent-build = { workspace = true }
log = { workspace = true }

[features]
default = ["web"]
# The feature that are only required for the web = ["dioxus/web"] build target should be optional and only enabled in the web = ["dioxus/web"] feature
web = ["dioxus/web"]

[profile]

[profile.wasm-dev]
inherits = "dev"
opt-level = 1

[profile.server-dev]
inherits = "dev"

[profile.android-dev]
inherits = "dev"

[lints]
workspace = true
