[application]

[web.app]

# HTML title tag content
title = "dioxus-example"

# include `assets` in web platform
[web.resource]

# Include i18n assets directory
assets = [ "../assets" ]

# Additional CSS style files
style = [  ]

# Additional JavaScript files
script = [  ]

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = [  ]
