"""Output writers for FTL and Rust files."""

from __future__ import annotations

from collections.abc import Iterable
from pathlib import Path


def escape_fluent_value(value: str) -> str:
    """Escape curly braces for Fluent format."""
    return value.replace("{", "{{").replace("}", "}}")


def write_ftl(output_path: Path, entries: Iterable[tuple[str, str]]) -> None:
    """Write locale entries to an FTL file.

    Args:
        output_path: Destination path for the FTL file.
        entries: Iterable of (locale_tag, display_name) tuples.
    """
    output_path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        f"es-fluent-lang-{locale} = {escape_fluent_value(name)}"
        for locale, name in entries
    ]
    _ = output_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def write_supported_locales(output_path: Path, locales: Iterable[str]) -> None:
    """Write supported locale keys to a Rust source file.

    Args:
        output_path: Destination path for the Rust file.
        locales: Iterable of locale tag strings.
    """
    output_path.parent.mkdir(parents=True, exist_ok=True)
    lines = ["// generated by scripts/cldr-es-fluent-lang/run.py\n"]
    lines.extend(["pub const SUPPORTED_LANGUAGE_KEYS: &[&str] = &["])
    lines.extend(f'    "{locale}",' for locale in locales)
    lines.append("];")
    _ = output_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
