# [unstable]
# codegen-backend = true
# [profile.server-dev]
# codegen-backend = "cranelift"

[alias]
es-fluent-local = "run -p es-fluent-cli -- es-fluent"
xtask = "run -p xtask --"

[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = [ "-C", "link-arg=-fuse-ld=mold" ]
