[package]
name = "first-example"
version = "0.1.0"
edition.workspace = true
license = "Unlicense"
publish = false

[dependencies]
es-fluent = { features = [ "derive" ], workspace = true }
es-fluent-manager-singleton = { workspace = true }
fluent = { workspace = true }
fluent-bundle = { workspace = true }
inventory = { workspace = true }
log = { workspace = true }
strum = { features = [ "derive" ], workspace = true }
unic-langid = { workspace = true }

[build-dependencies]
es-fluent-build = { workspace = true }
log = { workspace = true }

[lints]
workspace = true
