use anyhow::{Context, Result, bail};
use icu_experimental::displaynames::{
    DisplayNamesOptions, LocaleDisplayNamesFormatter,
    provider::{
        LanguageDisplayNamesV1, LocaleDisplayNamesV1, RegionDisplayNamesV1, ScriptDisplayNamesV1,
        VariantDisplayNamesV1,
    },
};
use icu_experimental_data::*;
use icu_locale::Locale;
use icu_provider::{DataMarker, IterableDataProvider};
use std::collections::{BTreeSet, HashMap};
use std::fs;
use std::path::{Path, PathBuf};

const I18N_RESOURCE_NAME: &str = "es-fluent-lang.ftl";
const GENERATED_HEADER: &str = "// generated by cargo run -p xtask -- generate-lang-names";

struct DisplayNamesProvider;

#[allow(unused_imports)]
const _: () = {
    pub mod icu {
        pub use icu_collections as collections;
        pub use icu_experimental as experimental;
        pub use icu_locale as locale;
        pub use icu_plurals as plurals;
    }

    make_provider!(DisplayNamesProvider);
    impl_language_display_names_v1!(DisplayNamesProvider, ITER);
    impl_locale_display_names_v1!(DisplayNamesProvider, ITER);
    impl_region_display_names_v1!(DisplayNamesProvider, ITER);
    impl_script_display_names_v1!(DisplayNamesProvider, ITER);
    impl_variant_display_names_v1!(DisplayNamesProvider, ITER);
};

pub fn run(
    ftl_output: Option<String>,
    rs_output: Option<String>,
    i18n_dir: Option<String>,
) -> Result<()> {
    let workspace = workspace_root()?;
    let default_ftl_output = workspace.join("crates/es-fluent-lang/es-fluent-lang.ftl");
    let default_rs_output = workspace.join("crates/es-fluent-lang-macro/src/supported_locales.rs");
    let default_i18n_dir = workspace.join("crates/es-fluent-lang/i18n");

    let ftl_output = resolve_path(ftl_output, &default_ftl_output);
    let rs_output = resolve_path(rs_output, &default_rs_output);
    let i18n_dir = resolve_path(i18n_dir, &default_i18n_dir);

    let supported_locales = discover_locales_from_icu4x()?;
    let parsed_locales = parse_target_locales(&supported_locales)?;

    let (display_locales, formatter_locales) = load_display_locales(&i18n_dir, &supported_locales)?;
    let formatter_locale_set: BTreeSet<&str> =
        formatter_locales.iter().map(String::as_str).collect();

    let locales_with_native_display: BTreeSet<&str> =
        formatter_locale_set.iter().copied().collect();

    let mut formatter_cache: HashMap<String, LocaleDisplayNamesFormatter> = HashMap::new();

    let mut autonym_entries = Vec::with_capacity(parsed_locales.len());
    let mut skipped_without_native = 0usize;
    for (locale_tag, locale) in &parsed_locales {
        let display_locale = choose_display_locale_for_autonym(locale_tag, &formatter_locale_set);
        if display_locale == "en" && !locales_with_native_display.contains(locale_tag.as_str()) {
            skipped_without_native += 1;
            continue;
        }
        let display_name = format_locale_name(&mut formatter_cache, &display_locale, locale)?;
        autonym_entries.push((locale_tag.clone(), display_name));
    }

    if skipped_without_native > 0 {
        println!(
            "Skipped {} locales without native display data",
            skipped_without_native
        );
    }

    println!(
        "Generating language names for {} locales and {} display locales...",
        autonym_entries.len(),
        display_locales.len()
    );

    write_ftl(&ftl_output, &autonym_entries)?;
    write_supported_locales(&rs_output, &supported_locales)?;

    let mut written_locales = 0usize;
    for display_locale in &display_locales {
        let formatter_locale =
            choose_display_locale_for_autonym(display_locale, &formatter_locale_set);
        let mut localized_entries = Vec::with_capacity(parsed_locales.len());
        for (locale_tag, locale) in &parsed_locales {
            let display_name = format_locale_name(&mut formatter_cache, &formatter_locale, locale)?;
            localized_entries.push((locale_tag.clone(), display_name));
        }

        let output_path = i18n_dir.join(display_locale).join(I18N_RESOURCE_NAME);
        write_ftl(&output_path, &localized_entries)?;
        written_locales += 1;
    }

    println!(
        "Wrote {} autonyms to {}",
        autonym_entries.len(),
        ftl_output.display()
    );
    println!(
        "Wrote {} supported locale keys to {}",
        supported_locales.len(),
        rs_output.display()
    );
    println!(
        "Wrote {} localized i18n files to {}",
        written_locales,
        i18n_dir.display()
    );

    Ok(())
}

fn workspace_root() -> Result<PathBuf> {
    let manifest_dir = Path::new(env!("CARGO_MANIFEST_DIR"));
    manifest_dir
        .parent()
        .map(Path::to_path_buf)
        .context("failed to resolve workspace root from xtask manifest directory")
}

fn resolve_path(value: Option<String>, default_path: &Path) -> PathBuf {
    value
        .map(PathBuf::from)
        .unwrap_or_else(|| default_path.to_path_buf())
}

fn parse_target_locales(locales: &[String]) -> Result<Vec<(String, Locale)>> {
    locales
        .iter()
        .map(|locale_tag| {
            let locale: Locale = locale_tag
                .parse()
                .with_context(|| format!("failed to parse locale tag '{locale_tag}'"))?;
            Ok((locale_tag.clone(), locale))
        })
        .collect()
}

fn canonicalize_locale_tag(locale_tag: &str) -> Result<String> {
    let locale: Locale = locale_tag
        .parse()
        .with_context(|| format!("failed to parse locale tag '{locale_tag}'"))?;
    Ok(locale.to_string())
}

fn discover_locales_from_icu4x() -> Result<Vec<String>> {
    let provider = DisplayNamesProvider;
    let mut locales = marker_locales::<LanguageDisplayNamesV1>(&provider, "language")?;

    let locale_locales = marker_locales::<LocaleDisplayNamesV1>(&provider, "locale")?;
    let region_locales = marker_locales::<RegionDisplayNamesV1>(&provider, "region")?;
    let script_locales = marker_locales::<ScriptDisplayNamesV1>(&provider, "script")?;
    let variant_locales = marker_locales::<VariantDisplayNamesV1>(&provider, "variant")?;

    locales.retain(|locale| locale_locales.contains(locale));
    locales.retain(|locale| region_locales.contains(locale));
    locales.retain(|locale| script_locales.contains(locale));
    locales.retain(|locale| variant_locales.contains(locale));

    if locales.is_empty() {
        anyhow::bail!("ICU4X compiled data did not provide any locales");
    }

    let result: Vec<String> = locales.into_iter().collect();
    println!(
        "Discovered {} locales from ICU4X compiled data",
        result.len()
    );
    Ok(result)
}

fn load_display_locales(
    i18n_dir: &Path,
    supported_locales: &[String],
) -> Result<(Vec<String>, Vec<String>)> {
    let formatter_locales = load_formatter_locales()?;
    let formatter_locale_set: BTreeSet<&str> =
        formatter_locales.iter().map(String::as_str).collect();
    let mut candidates = BTreeSet::new();

    if i18n_dir.is_dir() {
        for entry in fs::read_dir(i18n_dir)
            .with_context(|| format!("failed reading {}", i18n_dir.display()))?
        {
            let entry = entry.with_context(|| format!("failed reading {}", i18n_dir.display()))?;
            let file_type = entry
                .file_type()
                .with_context(|| format!("failed reading {}", entry.path().display()))?;
            if !file_type.is_dir() {
                continue;
            }
            let name = entry.file_name();
            let tag = name.to_string_lossy().trim().to_owned();
            if !tag.is_empty() {
                candidates.insert(tag);
            }
        }
    }

    if candidates.is_empty() {
        candidates.extend(supported_locales.iter().cloned());
    }

    let mut display_locales = Vec::new();
    for candidate in candidates {
        if candidate.parse::<Locale>().is_err() {
            continue;
        }
        let candidate_base = candidate.split('-').next().unwrap_or(&candidate);
        if !formatter_locale_set.contains(candidate.as_str())
            && !formatter_locale_set.contains(candidate_base)
        {
            continue;
        }
        display_locales.push(candidate);
    }

    display_locales.sort();
    display_locales.dedup();
    if display_locales.is_empty() {
        bail!("no usable output display locales were found");
    }

    Ok((display_locales, formatter_locales))
}

fn load_formatter_locales() -> Result<Vec<String>> {
    let provider = DisplayNamesProvider;
    let mut shared_locales = marker_locales::<LanguageDisplayNamesV1>(&provider, "language")?;

    let locale_locales = marker_locales::<LocaleDisplayNamesV1>(&provider, "locale")?;
    let region_locales = marker_locales::<RegionDisplayNamesV1>(&provider, "region")?;
    let script_locales = marker_locales::<ScriptDisplayNamesV1>(&provider, "script")?;
    let variant_locales = marker_locales::<VariantDisplayNamesV1>(&provider, "variant")?;

    shared_locales.retain(|locale| locale_locales.contains(locale));
    shared_locales.retain(|locale| region_locales.contains(locale));
    shared_locales.retain(|locale| script_locales.contains(locale));
    shared_locales.retain(|locale| variant_locales.contains(locale));

    if shared_locales.is_empty() {
        bail!("ICU4X compiled data did not provide any shared display locales");
    }

    Ok(shared_locales.into_iter().collect())
}

fn marker_locales<M>(provider: &DisplayNamesProvider, marker_name: &str) -> Result<BTreeSet<String>>
where
    M: DataMarker,
    DisplayNamesProvider: IterableDataProvider<M>,
{
    let ids = <DisplayNamesProvider as IterableDataProvider<M>>::iter_ids(provider)
        .with_context(|| format!("failed loading ICU4X {marker_name} display-name identifiers"))?;

    let mut locales = BTreeSet::new();
    for id in ids {
        if id.locale.is_unknown() {
            continue;
        }

        let raw = id.locale.to_string();
        let canonical = canonicalize_locale_tag(&raw).with_context(|| {
            format!("invalid ICU4X locale '{raw}' in {marker_name} display-name data")
        })?;
        locales.insert(canonical);
    }

    if locales.is_empty() {
        bail!("ICU4X {marker_name} display-name data did not provide any locales");
    }

    Ok(locales)
}

fn choose_display_locale_for_autonym(
    locale_tag: &str,
    display_locale_set: &BTreeSet<&str>,
) -> String {
    let mut segments = locale_tag.split('-').collect::<Vec<_>>();
    while !segments.is_empty() {
        let candidate = segments.join("-");
        if display_locale_set.contains(candidate.as_str()) {
            return candidate;
        }
        segments.pop();
    }

    if display_locale_set.contains("en") {
        return "en".to_owned();
    }
    if display_locale_set.contains("en-001") {
        return "en-001".to_owned();
    }

    display_locale_set
        .first()
        .map(|value| (*value).to_owned())
        .unwrap_or_else(|| "en".to_owned())
}

fn format_locale_name(
    formatter_cache: &mut HashMap<String, LocaleDisplayNamesFormatter>,
    display_locale: &str,
    target_locale: &Locale,
) -> Result<String> {
    if !formatter_cache.contains_key(display_locale) {
        let locale: Locale = display_locale
            .parse()
            .with_context(|| format!("failed to parse display locale '{display_locale}'"))?;
        let formatter =
            LocaleDisplayNamesFormatter::try_new(locale.into(), DisplayNamesOptions::default())
                .with_context(|| {
                    format!("failed to construct locale formatter for '{display_locale}'")
                })?;
        formatter_cache.insert(display_locale.to_owned(), formatter);
    }

    let formatter = formatter_cache
        .get(display_locale)
        .context("formatter cache unexpectedly missing display locale")?;
    Ok(formatter.of(target_locale).into_owned())
}

fn write_ftl(path: &Path, entries: &[(String, String)]) -> Result<()> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)
            .with_context(|| format!("failed to create {}", parent.display()))?;
    }

    let content = entries
        .iter()
        .map(|(locale, name)| format!("es-fluent-lang-{locale} = {}", escape_fluent_value(name)))
        .collect::<Vec<_>>()
        .join("\n")
        + "\n";

    fs::write(path, content).with_context(|| format!("failed to write {}", path.display()))?;
    Ok(())
}

fn write_supported_locales(path: &Path, locales: &[String]) -> Result<()> {
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)
            .with_context(|| format!("failed to create {}", parent.display()))?;
    }

    let mut content = String::new();
    content.push_str(GENERATED_HEADER);
    content.push('\n');
    content.push('\n');
    content.push_str("pub const SUPPORTED_LANGUAGE_KEYS: &[&str] = &[\n");
    for locale in locales {
        content.push_str("    \"");
        content.push_str(locale);
        content.push_str("\",\n");
    }
    content.push_str("];\n");

    fs::write(path, content).with_context(|| format!("failed to write {}", path.display()))?;
    Ok(())
}

fn escape_fluent_value(value: &str) -> String {
    value.replace('{', "{{").replace('}', "}}")
}
