[package]
name = "iced-example"
version.workspace = true
edition.workspace = true
license = "Unlicense"
publish = false

[dependencies]
es-fluent = { features = [ "derive" ], workspace = true }
es-fluent-manager-singleton = { workspace = true }
iced = { workspace = true, features = ["tiny-skia", "web-colors"] }
rust-embed = { workspace = true }
strum = { features = [ "derive" ], workspace = true }
unic-langid = { workspace = true }
example-shared-lib = { path = "../example-shared-lib", features = ["gpui"] }

[build-dependencies]
es-fluent-build = { workspace = true }
log = { workspace = true }

[lints]
workspace = true
