[package]
name = "es-fluent-toml"
edition.workspace = true
license.workspace = true
publish.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
serde = { features = [ "derive" ], workspace = true }
thiserror = { workspace = true }
toml = { workspace = true }

[lints]
workspace = true
