name: ci

on:
  pull_request:
  push:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: dtolnay/rust-toolchain@stable
      - name: Setup mold
        uses: rui314/setup-mold@v1
      - name: Install Linux dependencies
        uses: ./.github/actions/install-linux-deps

      - name: Run tests
        run: cargo test --all-features

  fmt:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - name: Setup mold
        uses: rui314/setup-mold@v1
      - name: Install Linux dependencies
        uses: ./.github/actions/install-linux-deps

      - name: Check formatting
        run: cargo fmt --check

  clippy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - name: Setup mold
        uses: rui314/setup-mold@v1
      - name: Install Linux dependencies
        uses: ./.github/actions/install-linux-deps

      - name: Lint code
        run: cargo clippy --workspace --all-features --exclude cosmic-example -- -D warnings
