[application]
asset_dir = "public"
name = "es-fluent"
out_dir = "dist"

[web.app]
base_path = "es-fluent"
title = "es-fluent"

[web.watcher]
index_on_404 = true
reload_html = true
watch_path = [ "src", "public", "assets" ]

[web.resource]
script = [  ]
style = [  ]

[web.resource.dev]
script = [  ]
style = [  ]
